install android studio, flutter prereqs, and flutter bash scrips complete.

diff --git a/bin/install_flutter b/bin/install_flutter
--- a/bin/install_flutter
+++ b/bin/install_flutter
@@ -18,8 +18,7 @@ else
     PATH_TO_FL="$1"
 
     echo "Unpacking $PATH_TO_FL to $DEST_DIR"
-    tar -xf "$PATH_TO_FL" -C "$DEST_DIR"
-if [ ! $? ]; then
+    if ! tar -xf "$PATH_TO_FL" -C "$DEST_DIR"; then
         echo "Failed to unpack $PATH_TO_FL."
         exit 1
     fi
@@ -30,19 +29,27 @@ BIN_PATHS="$DEST_DIR/flutter/bin"
 FLUTTER_PATH="$BIN_PATHS/flutter"
 DART_PATH="$BIN_PATHS/dart"
 
-$FLUTTER_PATH --version
-if [ ! $? ]; then
+if ! $FLUTTER_PATH --version; then
     echo "Flutter not installed successfully."
     exit 1
 fi
 
-$DART_PATH --version
-if [ ! $? ]; then
+if ! $DART_PATH --version; then
     echo "Dart not installed successfully."
     exit 1
 fi
 
+echo "Installing requisites clang, CMake, ninja, libgtk-3dev, and pkg-config ..."
+if ! apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev; then
+    echo "❌ Failed to install clang, CMake, ninja, and pkg-config."
+    exit 1
+fi
+echo "✅ clang, CMake, ninja, libgtk-3-dev, and pkg-config installed."
+
 echo "Ready to go with Flutter and Dart!"; echo
 echo "Make sure to add to PATH: $BIN_PATHS"; echo
 
-env PATH="$PATH:$BIN_PATHS" flutter doctor
+env PATH="$PATH:$BIN_PATHS" flutter doctor; echo
+
+echo "❗ Andriod Studio may not show as being installed."
+echo "Run 'flutter doctor' as user to check installation status."
